dist: trusty
sudo: false

language: scala

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8
  - openjdk11

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "cpqMHGD08JMt0RwgIUl381yR1Iur2a+kD/KDPhcHjQdx0ZYXXCX5jbjeM9kJNGn5u5mbQppfY23335Qg8XbeI+MGbC6EyH2qTg0i13ZG79Jz3ERDthgBkxTdvd2riHgEi9gDM0gYiciVQptrKlL68QsoxnaVTPF8BAhilKcUw1sChzzBnX94sRWnkBLE0j9TYcTUjU4zY12w3c8ySHRiICDKM6J+C5/OPG4jD+rynzU7O8depcuCRrLuLiih+Xru0o/Vg/ktrTPgVCLB6a+GYgeuBrP9hl5wcVNi8esmGSCVpz9tXZP7u3BGmG0FuU5e0iDn/vLJ0mm6700MT+xwt6570FGhwkQlZdo4KfZigElJGLThW6JJoGtfkm1vRWcK/RUdyQ/XkdZD+sUQKrugd5qZikpdjmnYbz9I7ZpOWFQhuWkuL4zUqfgnudc1SdsnlmpZRPtVyE5VQJWHqkipGoFuashPSv3gl6qo9JRgDWJBCaaI24tr/mv4vCzXLesW8ZQqUnL2/CZNvQRft04nPrIlWPQXpyblHC47NEW8J3kuoDQrGtqKM59rkjdjcP8xhfHC1DS+8YUG7KqdZbQe15rynh657tywp54o1vM8UvvqTpeigyhnn6V5RARanTOn540rGjAVFVvwZkObsIX8jy25Aq/Md31R7ibQkFyTYQk="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete